services:
  app:
    build: .
    image: devops
    container_name: devops
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www/devops
    volumes:
      - .:/var/www/devops
      - ./storage/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - devops

  webserver:
    image: nginx:alpine
    container_name: nginxdevops
    restart: unless-stopped
    tty: true
    ports:
      - "2022:80"
    volumes:
      - .:/var/www/devops
      - ./storage/:/etc/nginx/conf.d
    networks:
      - devops

  db:
    image: mysql:5.7
    container_name: dbdevops
    restart: always
    tty: true
    ports:
      - "20222:3306"
    volumes:
      - lbdata:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: devops
      MYSQL_ROOT_PASSWORD: devops
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - devops

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pmadevops
    links:
      - db
    restart: always
    ports:
      - "7000:80"
    networks:
      - devops

networks:
  devops:
    driver: bridge

volumes:
  lbdata:
    driver: local
